### ISSUE TITLE
Using pytorch data-loading with jraph.

### ISSUE THREAD

**Issue by engmubarak48** [deepmind/jraph#31]
Hi, 

Thanks for the great library. I created this Toy example of how to combine PyTorch geometric data-loading and Jraph. Let me know if it is useful to make it a tutorial/example, and also if more descriptions are needed.

Link: https://drive.google.com/file/d/1_X2su92_nS52RNl4m-WYvmkvUSrFE4xQ/view?usp=sharing

**Comment by jg8610** [comment]
Thank you, I really appreciate it - I will give it a read over.

If you're happy, I would really like to add this as an example or link to this from the central github repo.

**Comment by engmubarak48** [comment]
Hi,

Sure I will refactor it. 

Also, I like your idea of just keeping to the data-loading, and leaving the modeling part. So I will make it that way. 

Thanks.

**Comment by engmubarak48** [comment]
Hi @jg8610 

Can you check now, if it is better? kind of removed all the rest of the code.

**Comment by jg8610** [comment]
Thanks! I was OOO last week will have a look today.

**Comment by engmubarak48** [comment]
Hi, 

Done as per your suggestions. Do we have a similar notebook for tf.data.dataset options? if so can you share it with me?

**Comment by jg8610** [comment]
The OGBG Molpca notebook uses tf data, but in order to use tfdata well you need to do a bit of work to add your dataset to the central repository.

**Comment by jg8610** [comment]
But, this is great! I will add a link to this colab in the readme next week.

**Comment by onnoeberhard** [comment]
There seems to be a bug in this notebook (perhaps due to a newer version of pytorch-geometric). When creating the `ToyDataset` object in cell 5, the following error is raised: `TypeError:  Can't instantiate abstract class ToyDataset with abstract methods get, len`. I don't know exactly what the purpose of the methods `len` and `get` is in `Dataset`, because they don't replace `__len__` and `__getitem__`. Adding the following two methods to `ToyDataset` seems to at least solve the issue:
```python
def len(self):
    return len(self)

def get(self, idx):
    return self[idx]
```
Just adding empty (`pass`) methods `len` and `get` also works..
